# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordao',
            fields=[
                ('id_processo', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('URL', models.URLField(max_length=500)),
                ('URL_inteiro_teor', models.URLField(max_length=500)),
                ('URL_dj_dj3', models.URLField(blank=True, max_length=500)),
                ('HTML', models.TextField()),
                ('texto', models.TextField(blank=True)),
                ('inteiro_teor', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
