# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stfcrawler', '0002_auto_20170328_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acordao',
            old_name='HTML',
            new_name='HTML_texto_basico',
        ),
        migrations.RenameField(
            model_name='acordao',
            old_name='inteiro_teor',
            new_name='pdf_inteiro_teor',
        ),
        migrations.RenameField(
            model_name='acordao',
            old_name='texto',
            new_name='texto_basico',
        ),
        migrations.AddField(
            model_name='acordao',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='acordao',
            name='classe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='acordao',
            name='codigoClasse',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='acordao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acordao',
            name='origem',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='acordao',
            name='recurso',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='acordao',
            name='texto_inteiro_teor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='acordao',
            name='tipoJulgamento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='acordao',
            name='txt_inteiro_teor',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
